version: '3'
services:
  app:
    container_name: go-assignment
    build: .
    ports:
      - 8081:8081
    restart: on-failure
#    volumes:
#      - api:/usr/src/app
    depends_on:
      - database


  database:
    container_name: sql_db
    image: "mysql"
    environment:
      - MYSQL_ROOT_HOST=${DB_HOST}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
#    volumes:
#      - database_mysql:/var/lib/mysql